name: shovel
description: A lightweight dependency injection framework for Dart applications that provides an intuitive way to manage dependencies.
version: 1.0.0+2
repository: https://github.com/SoutaTanaka/shovel
homepage: https://x.com/_sotaatos

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0
